services:
  backend:
    image: openjdk:17-jdk
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/.m2:/root/.m2
      - ${HOME}/Documents/estudos/projetos/house_manager/house_manager_api:/app
    environment:
      - POSTGRES_DB=house_manager
    networks:
      - spring-postgres
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - db
  db:
    image: postgres
    platform: linux/x86_64
    restart: always
    ports:
      - 5432:5432
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=house_manager
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - "5432"
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
